language: java
jdk:
  - openjdk8
  - oraclejdk9
  - openjdk10
  - oraclejdk11

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"

deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: "build/libs/*"
    skip_cleanup: true
    on:
      tags: true
      condition: $GITHUB_TOKEN != ""
      jdk: oraclejdk11
